
export const OPEN_CART_LIST = 'OPEN_CART_LIST';
export const CLOSE_CART_LIST = 'CLOSE_CART_LIST';

export const ADD_PRODUCT_TO_CART = '@cart/ADD_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_IN_CART = '@cart/UPDATE_PRODUCT_IN_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const RESTORE_CART = '@cart/RESTORE_CART';
export const RESET_CART = '@cart/RESET_CART';